Fix missing autocomplete results in dialogs
pombase/canto pull request #2374
Opened 2020-12-07 21:35 UTC by kimrutherford

(Replaces #2373)

After a bunch of Google searching I found a better solution, documented here: https://api.jqueryui.com/autocomplete/#option-appendTo

I've added a "ui-front" class to the dialog HTML and that seems to do the trick.   For now I've just added it to the two dialog templates that I think need it, but there might be other places.

2020-12-08 14:33 UTC, jseager7 requested changes
I've tested this and it seems to work fine. Both the experimental conditions picker and the term lookup render in front of the modal. 

During testing I found that the allele name autocomplete is also affected by this bug, but I'm not sure how to fix it. Putting the `ui-front` class on the element containing the `input` element didn't seem to fix anything. Here's what it should look like:

![image](https://user-images.githubusercontent.com/37659591/101496516-c682bd80-3961-11eb-94af-9737ebae54ee.png)

You can get to this modal through the 'Other genotype' button on the Genotype management page.

There might be other autocomplete fields out there, but I couldn't locate them in the interface. I think that the following text can be used to locate code using the autocomplete in `canto-modules.js`:

```js
.data("autocomplete")._renderItem = function (ul, item)
```

Based on testing it seems the search pattern can be shortened to just `"autocomplete"`.

Using this search I found references to an autocomplete in the following directives:

- `alleleNameComplete`
- `featureComplete`
- `termNameComplete`

`termNameComplete` seems to be fixed already, and `alleleNameComplete` is described above, but I don't know where (or when) `featureComplete` appears in the interface.

2020-12-08 22:11 UTC, kimrutherford commented
> During testing I found that the allele name autocomplete is also affected by this bug,

Thanks for testing.  I've pushed a fix for that.

> Putting the ui-front class on the element containing the input element didn't seem to fix anything.

I added ui-front to the element with the modal-content class in allele_edit.html and that seemed to work.

> but I don't know where (or when) featureComplete appears in the interface.

I think it's only used in one place at the moment.  If you're editing an genotype-phenotype annotation there's a search button beside the genotype selector, which turns the selector into an autocomplete box.  I think this case is covered by the previous fixes.

![genotype-search-1](https://user-images.githubusercontent.com/90474/101547413-1075ad00-3a0f-11eb-992d-14ae46fe7323.png)

2020-12-09 10:25 UTC, jseager7 approved these changes

2020-12-09 10:26 UTC, jseager7 commented
Thanks for the fix. I've tested all of the remaining autocomplete fields and they all draw in front of the modal, as expected. I'll go ahead and merge this.

2020-12-09 10:27 UTC, merged